# Generated by Django 5.0.4 on 2025-02-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_campaign_surveyforms_type_alter_surveyforms_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationitems',
            name='survey',
            field=models.TextField(blank=True, null=True),
        ),
    ]
