# Generated by Django 5.0.4 on 2025-02-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_validationitems_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationregister',
            name='document_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
