# Generated by Django 5.0.4 on 2025-02-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_argeliagrupos_argeliapersonas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationregister',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
