# Generated by Django 3.2.15 on 2025-02-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormCatatumboPreregistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posee_predios', models.BooleanField(blank=True, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('victima_desplazamiento', models.BooleanField(blank=True, null=True)),
                ('actividades_transitar', models.CharField(blank=True, max_length=255, null=True)),
                ('actividades_economicas', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
