# Generated by Django 3.2.15 on 2025-02-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcatatumbopreregistro',
            name='linea_productiva',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
