# Generated by Django 5.0.4 on 2025-02-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_formcatatumbopreregistro_linea_productiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCatatumboPreinscripcionNucleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupa_predio_cultivo_ilicito', models.BooleanField(blank=True, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
