# Generated by Django 5.0.4 on 2025-02-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_formcatatumbopreinscripcionnucleo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCatatumboPreinscripcionDesplazados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupa_predio_cultivo_ilicito', models.BooleanField()),
                ('numero_documento', models.CharField(max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
