# Generated by Django 5.0.4 on 2025-02-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_formcatatumbopreinscripciondesplazados'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCatatumboPreinscripcionGrupoProductores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion_asociados', models.BooleanField()),
                ('victimas_desplazamiento', models.BooleanField(blank=True, null=True)),
                ('actividad_transito', models.CharField(blank=True, max_length=50, null=True)),
                ('actividad_etapa', models.CharField(blank=True, max_length=50, null=True)),
                ('linea_productiva', models.CharField(blank=True, max_length=50, null=True)),
                ('linea_productiva_otra', models.CharField(blank=True, max_length=100, null=True)),
                ('actividad_economica', models.CharField(blank=True, max_length=100, null=True)),
                ('experiencia_tiene_experiencia', models.BooleanField(blank=True, null=True)),
                ('experiencia_agnos', models.FloatField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=50, null=True)),
                ('vereda', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo_nombre', models.CharField(max_length=200)),
                ('grupo_tipo', models.CharField(max_length=100)),
                ('grupo_num_registro', models.CharField(blank=True, max_length=100, null=True)),
                ('lider_nombre', models.CharField(max_length=200)),
                ('lider_identificacion', models.CharField(max_length=50)),
                ('grupo_telefonos', models.CharField(blank=True, max_length=200, null=True)),
                ('grupo_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('departamento_cobertura', models.CharField(max_length=100)),
                ('veredas_cobertura', models.CharField(max_length=200)),
                ('grupo_fecha_creacion', models.DateField()),
                ('lineas_productivas', models.TextField()),
                ('lineas_otro', models.CharField(blank=True, max_length=200, null=True)),
                ('departamento_creacion', models.CharField(max_length=100)),
            ],
        ),
    ]
