# Generated by Django 5.0.4 on 2025-02-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_formcatatumbopreinscripciongrupoproductores'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCatatumboPreinscripcionNucleosIndividuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo_position', models.CharField(max_length=10)),
                ('ocupacion_beneficiario', models.BooleanField()),
                ('victimas_desplazamiento', models.BooleanField()),
                ('actividad_transito', models.CharField(blank=True, max_length=50, null=True)),
                ('actividad_etapa', models.CharField(max_length=50)),
                ('actividad_economica', models.CharField(blank=True, max_length=100, null=True)),
                ('experiencia_tiene_experiencia', models.BooleanField()),
                ('experiencia_agnos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tiene_formacion', models.BooleanField()),
                ('departamento', models.CharField(max_length=100)),
                ('cabecera_centropoblado', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('foto_frente', models.TextField(blank=True, null=True)),
                ('foto_respaldo', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('tiene_identidad_genero', models.BooleanField(blank=True, null=True)),
                ('numero_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('etnia_identificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('organizacion_pertenece', models.CharField(blank=True, max_length=255, null=True)),
                ('resguardo_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicado_territorio_etnico', models.CharField(blank=True, max_length=100, null=True)),
                ('condicion', models.CharField(blank=True, max_length=100, null=True)),
                ('discapacidad', models.BooleanField(blank=True, null=True)),
                ('educacion', models.CharField(blank=True, max_length=100, null=True)),
                ('num_personas_nucleo', models.PositiveIntegerField(blank=True, null=True)),
                ('num_doc_personas_nucleo', models.TextField(blank=True, null=True)),
                ('nombres_apellidos_nucleo', models.TextField(blank=True, null=True)),
                ('num_predios_relevancia', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('vereda', models.CharField(blank=True, max_length=255, null=True)),
                ('vereda_otro', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_acceso', models.TextField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_coca', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('relacion_tenencia', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_relacion_tenencia', models.TextField(blank=True, null=True)),
                ('longitud', models.CharField(blank=True, max_length=50, null=True)),
                ('latitud', models.CharField(blank=True, max_length=50, null=True)),
                ('altitud', models.CharField(blank=True, max_length=50, null=True)),
                ('precision', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
