# Generated by Django 5.0.4 on 2025-02-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_formcatatumbopreinscripcionnucleosindividuales'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCatatumboPreregistroFamiliasPnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('victima_desplazamiento', models.BooleanField(blank=True, null=True, verbose_name='¿Ha sido víctima de desplazamiento forzado después del 15 de enero de 2025?')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('numero_telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de teléfono celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección o referencia del predio')),
                ('acepta_terminos', models.BooleanField(default=False, verbose_name='Acepta términos y condiciones')),
                ('acepta_tratamiento_datos', models.BooleanField(default=False, verbose_name='Acepta tratamiento de datos personales')),
            ],
        ),
    ]
