# Generated by Django 5.0.4 on 2025-02-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_formcatatumbopreregistrofamiliaspnis'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcatatumbopreregistrofamiliaspnis',
            name='vereda',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Veredafamilias'),
        ),
        migrations.AlterField(
            model_name='formcatatumbopreregistrofamiliaspnis',
            name='acepta_terminos',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Acepta términos y condiciones'),
        ),
        migrations.AlterField(
            model_name='formcatatumbopreregistrofamiliaspnis',
            name='acepta_tratamiento_datos',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Acepta tratamiento de datos personales'),
        ),
    ]
